### ISSUE TITLE
use msg.respond instead of msg.reply

### ISSUE THREAD

**Issue by tenfourty** [mukundha/aar-bot#1]
https://github.com/mukundha/aar-bot/blob/master/src%2Frfp.js#L31

msg.reply does a reply to the person, which I don't think we need:

me> rfp soa
chatbot> **jeremybrown**: Question: Are both SOAP and REST supported?
[...]

Don't forget to bump the version in your package.json if you change something ;-)

**Comment by mukundha** [comment]
this was easy, but there was no respond, so i used msg.send() - now the name is removed. Thank you
